version: '3.8'

services:
  web:
    container_name: web_app
    image: pythonapp
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql11/data


volumes:
  pgdata: {}